config/routes.rb
Rails.application.routes.draw do
  resources :songs
  devise_for :users
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'song/random_song', to: 'songs#random_song', as: 'random_song'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  validates :author, :public, :title, :time, presence: true
  enum public: [:yes, :no]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.where(user_id: current_user.id).or(Song.where(public: "yes"))
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    @song.user_id = current_user.id

    respond_to do |format|
      if @song.save
        format.html { redirect_to songs_path, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def random_song
    random_song = Song.where(user_id: current_user.id).or(Song.where(public: "yes")).map {|song| song.id}.sample
    # song = Song.find(random_song)
    # params[:id] = random_song
    redirect_to song_path(random_song)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :author, :time, :public, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/index.html.erb
<h1>CDV Song Docker App</h1>
<h2>Hello <%= current_user.email %></h2>

<!--<button type="button" class="btn btn-primary"><%#= link_to 'Songs', songs_path, class: "text-dark btn" %></button>-->
<%#= button_to "delete", destroy_user_session_path, :method => "delete" %>

<div class="card-group">
  <div class="card">
    <img class="card-img-top" src="https://applemobile.pl/wp-content/uploads/2018/04/Ikona1-6.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Best Music</h5>
      <p class="card-text">Only Best music in WEB!</p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="http://www.fumcwl.org/files/69/Pictures/music.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Listen Everywhere</h5>
      <p class="card-text">Your best music on every device whit internet connection</p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="http://www.pngmart.com/files/3/Music-PNG-Photos.png" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Upload</h5>
      <p class="card-text">Share music whit friends!</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dockersongapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div clalss="container-fluid" >
<!--  <p class="notice"><%#= notice %></p>-->
<!--  <p class="alert"><%#= alert %></p>-->
  <% if user_signed_in? %>
<!--    <button type="button" class="btn btn-primary"><%#= link_to 'Songs', songs_path, class: "text-dark btn" %></button>-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= button_to 'Menu', root_path, :class => "btn btn-light", :method => 'get' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
           <%= button_to 'Songs', songs_path, :class => "btn btn-primary btn-lg btn-block", :method => 'get' %>
          </li>
          <li class="nav-item active">
            <%= button_to 'Upload song', new_song_path, :class => "btn btn-secondary btn-lg btn-block", :method => 'get' %>
          </li>
<!--          <li class="nav-item">-->
            <%#= button_to "logout", destroy_user_session_path, :method => "delete" , :class => "btn btn-danger" %>
<!--          </li>-->
          <li class="nav-item">
            <%= button_to "Edit account", edit_user_registration_path(current_user), :method => 'get' , :class => "btn btn-warning btn-lg btn-block" %>
          </li>

        </ul>
        <ul class="navbar-nav mr-right">
        <li class="nav-item unstyled">
          <%= button_to "logout", destroy_user_session_path, :method => "delete" , :class => "btn btn-danger btn-lg btn-block" %>
        </li>
        </ul>

<!--        <form class="form-inline my-2 my-lg-0">-->
<!--          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--        </form>-->
      </div>
    </nav>
  <%#= link_to('Logout', destroy_user_session_path, method: :delete) %>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/songs/_form.html.erb
<center>
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :user_id %>
    <%#= form.number_field :user_id %>
<!--  </div>-->

  <div class="field">
    <%= form.label :public %>
    <%= form.select :public, options_for_select(Song.publics.keys) %>
  </div>

  <%= form.label :text %>
  <div class="field">
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</center>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>
<!--<div class="spinner-border" role="status">-->
<!--  <span class="sr-only">Loading...</span>-->
<!--</div>-->


<%= button_to 'Random Song', random_song_path, method: :get, class: "btn btn-info " %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Time</th>
      <th>User</th>
      <th>Play</th>
      <th> Edit </th>
      <th> Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.author %></td>
        <td><%= song.time %></td>
        <td><%= song.user_id %></td>
        <td><%= button_to 'Play', song , method: :get%></td>
        <% if song.user == current_user %>
        <td><%= button_to 'Edit', edit_song_path(song), method: :get %></td>
        <td><%= button_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>




<br>

app/views/songs/new.html.erb
<center>

<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>
</center>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Playing <%= @song.title %></h1>


<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Time</th>
    <th>User</th>
    <th>Play</th>
<!--    <th> Edit </th>-->
<!--    <th> Destroy</th>-->
  </tr>
  </thead>

  <tbody>
  <tr>
    <td><%= @song.title %></td>
    <td><%= @song.author %></td>
    <td><%= @song.time %></td>
    <td><%= @song.user_id %></td>
    <td><div class="spinner-border" role="status">
      <span class="sr-only"></span>
    </div></td>
  </tr>
  </tbody>
</table>


<div class="card text-center">
  <div class="card-header">
  </div>
  <div class="card-body">
    <h5 class="card-title">Song Text</h5>
    <p class="card-text"> <%= @song.text %></p>
  </div>
</div>


<!--<%#= link_to 'Edit', edit_song_path(@song) %> |-->
<%#= link_to 'Back', songs_path %>